
name: bets
# PRODUCTION only
services:
  backend:
    profiles:
      - dev
      - staging
      - prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bets-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_RELOAD=true
      - PROJECT_BASE_PATH=/app
      - DATABASE_URL=postgresql+psycopg://bets_user:bets_password@postgres:5432/bets_db
    volumes:
      - ./backend:/app
    restart: unless-stopped # always instead ?
    networks:
      - bets-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    profiles:
      - staging
      - prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bets-frontend
    ports:
      - "3000:3000"
    environment:
      - PYTHON_API_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - bets-network

  postgres:
    profiles:
      - dev
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    environment:
      POSTGRES_USER: bets_user
      POSTGRES_PASSWORD: bets_password
      POSTGRES_DB: bets_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql  
      # - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bets_user -d bets_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
networks:
  bets-network:
    driver: bridge




  # pgAdmin for database management (optional)
  # might use as we use for literacy ??
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: bets_pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@bets.local
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
